### ISSUE TITLE
QoL request

### ISSUE THREAD

**Issue by Berytak** [frondeus/fvtt-syrin-control#15]
Hey there,

first of all "THIS" is the module I've wanted most. It makes handling Syrinscape a breeze. No need for a second monitor or window.
Now to the Qol requests:

- If you press the stop button underneath the mood, the soundset and mood fields are cleared. It would be great if both would stay selected and just the mood stops.
- It would be great If the one-shot buttons could be resized. They take a fair chunk of screenspace due to the huge icons. Half the size would be enough. Here is a comparison between FVTT and Syrinnscape.
![image](https://user-images.githubusercontent.com/85394657/143824729-ca7cc308-a4b6-4813-9adb-f240e52613f4.png) ![image](https://user-images.githubusercontent.com/85394657/143824884-ace7cf2f-f00b-45cb-b5fc-06595a9e5fd7.png)

btw, is there a way I can show you my gratitude for this module so you can buy yourself a coffee? 

Cheers Berytak

**Comment by frondeus** [comment]
Hi,

First of all, thanks for using this module!
About your requests:
* Yeah, it was a design decision, probably the wrong one. I need to fix that.
* True, the whole application needs a renovation

I will touch these two as soon as I finish my refactor. The 0.1.0 release was more a prototype, and now I need to clean a lot of things before adding new features and polishing UX. Otherwise, I will bury myself in spaghetti code.

Therefore it might take a while to finish this issue.

AD Btw: I... didn't expect this, and I'm flattered. I will have to think about it :)

**Comment by Berytak** [comment]
Take your time! There is nothing more frustrating than overlooking some stuff due to a hurry ;-)

**Comment by frondeus** [comment]
Hi @Berytak, I just released pre-release 0.2.0-pre2: https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.2.0-pre2
It should work just fine, and you could use a link to manifest to install it in your Foundry instance if you want to test it.

I need an extra couple of days to polish everything in the codebase, prepare new documentation, README, screenshots, etc. before I release it in Foundry as a stable release.

Merry Christmas and Happy New Year!

**Comment by Berytak** [comment]
Hey @frondeus ,
sure thing that I'll test the new version, but I'm a bit puzzled how to install it. If I paste the URL into the manifest install field I get an error message.
![image](https://user-images.githubusercontent.com/85394657/147548900-ca8e738d-952b-4f65-a5da-56d7c40f222b.png)
Tried the URL with and witout the module.json.
Any idea what I'm doing wrong? Do I just download it and copy the files into the module folder?

Cheers!
Berytak

**Comment by frondeus** [comment]
Let me check it quickly in an hour , it should be working but I only tested it on local machine with V9 installed

**Comment by frondeus** [comment]
@Berytak please check https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.2.0-pre3 - I fixed the issue, now I can download it both in V9 and 8.8

**Comment by Berytak** [comment]
@frondeus Can you please provide me the full link you paste into the manifest URL field? I'm still getting the same error and I guess it's some kind of user error 😏

**Comment by frondeus** [comment]
@Berytak  Absolutely! It is a link to module.json:
https://github.com/frondeus/fvtt-syrin-control/releases/download/0.2.0-pre3/module.json

**Comment by Berytak** [comment]
@frondeus Thank you, that worked like a charm! What I've seen so far is pretty brilliant. The icon size for the one-shots is much better and I really like it, that I can add moods to a playlist. It's just a shame, that the search button is gone.
btw, I've seen that it'll load all the syrinscape icons on the one-shots for you. What do I have to do to get the same behaviour?
I would guess, that it's the API driven connection and not the CSV one, am I correct?

**Comment by frondeus** [comment]
I am going to reintroduce search button - but as a standalone feature not depending on quick insert hack :)

**Comment by frondeus** [comment]
About icons - unfortunately, yes - CSV does not provide links to icons, online API does.
I am closing this issue :) Happy New Year!

**Comment by Berytak** [comment]
Thank you for your efford!
Happy New Year!
